### ISSUE TITLE
A mistake occurred when retrieving branch name from git repository via File IO Implementation

### ISSUE THREAD

**Issue by ExerciseBook** [vanBassum/Wakatime.Unity#11]
https://github.com/vanBassum/Wakatime.Unity/blob/08f29761573924b7d392f8ab19181a39fc47fa52/Editor/HeartbeatCollector.cs#L184

A branch name contains `/` is acceptable.

e.g: https://github.com/dotnet/runtime

![image](https://user-images.githubusercontent.com/6327311/215677288-061d6318-3646-486c-979f-41409b94aa4a.png)

assign to: @buger404 

---

When we read `.git/HEAD`, there are a few situations

1. we got `ref: refs/heads/master`. A reference name of a commit
2. we got `08f29761573924b7d392f8ab19181a39fc47fa52`. A plain commit id

Maybe more? I am not sure.

**Comment by buger404** [comment]
Thanks for reminding, I'll try to fix the problem later.
I should consider it more comprehensively.

**Comment by vanBassum** [comment]
Ah, I was afraid of these type of situations. Thats why I didn't remove the old solution. I guess its more robust to use either the git cli or a git .net package

**Comment by buger404** [comment]
I created a new pull request #12 to fix this issue.

**Comment by vanBassum** [comment]
I've merged your pull request, therefore this issue is resolved.
