### ISSUE TITLE
Engine Bug

### ISSUE THREAD

**Issue by maxtyson123** [vanBassum/Wakatime.Unity#21]
When running in unity 2023.2.3f1 this error occurs: 
In order to call GetTransformInfoExpectUpToDate, RendererUpdateManager.UpdateAll must be called first.
UnityEngine.GUIUtility:ProcessEvent (int,intptr,bool&)

And the time in the dashboard stays 0

**Comment by vanBassum** [comment]
Thanks for reporting the issue, I expect that it will be a while before I find the time to fix the issue.

**Comment by vanBassum** [comment]
I don't think the plugin calls the GetTransformInfoExpectUpToDate function.
Are you sure it has to-do with this plugin?

I will close the issue for now, if the issue still persists, feel free to re-open the issue.

**Comment by maxtyson123** [comment]
That was half a year ago….

Max Tyson
