### ISSUE TITLE
Every heartbeat opens a cmd window for a brief moment on Windows

### ISSUE THREAD

**Issue by mai-soup** [vanBassum/Wakatime.Unity#5]
Can't see what exactly it's doing as it only flashes for a split second, but it's quite annoying, especially when several heartbeats are done in succession.

**Comment by vanBassum** [comment]
Wow, I see, this is a very annoying behavior. However, I don't have the slightest idea what might cause this. I'll have to do some digging.

**Comment by buger404** [comment]
The issue appears again on Windows 11, plugin version 0.1.0.
Every heartbeat opens a 'Windows Terminal' window for a brief moment.
